# Generated by Django 4.1.1 on 2022-09-25 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название объявления')),
                ('text', models.TextField(verbose_name='Текст объявления')),
                ('category', models.CharField(choices=[('tanks', 'Танки'), ('heals', 'Хилы'), ('dd', 'ДД'), ('traders', 'Торговцы'), ('givers', 'Квестгиверы'), ('smiths', 'Кузнецы'), ('tanners', 'Кожевники'), ('potions', 'Зельевары'), ('spellcasters', 'Мастера заклинаний')], default='tanks', max_length=12, verbose_name='Категория')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('attach', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Вложение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Resp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_board.advert', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
